### PR TITLE
Shorten package description

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by purcell** [comment]
In connection with https://github.com/melpa/melpa/pull/4988

**Comment by alphapapa** [comment]
Thanks, that's definitely clearer and more concise, but isn't it important to say that it's a library, i.e. not something for users to use directly?  There are no interactive commands, it's just for package authors.

**Comment by purcell** [comment]
Sure. I guess I felt it might be redundant. You could edit the PR to prefix it with `Library to `.

**Comment by alphapapa** [comment]
Thanks, Steve!

**Pull request closed without merging**
